#
# ~/.bashrc
#

source ~/.profile

if [[ $(tty) = /dev/tty1 ]]; then
	exec Hyprland
fi

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'

alias f='ranger'
alias r='ranger'
#
# fzf
alias ff='nvim $(find * -type f | fzf)'
alias fd="cd ~ && cd \$(find * -type d | fzf)"

alias ls='ls --color=auto'

alias tarnow='tar -acf '
alias untar='tar -zxvf '

PS1='[\u@\h \W]\$ '
