export EDITOR='nvim'
export OPENAI_API_KEY="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"
export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_SDK_ROOT=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=100000
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/stian/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

eval "$(starship init zsh)"

# ALIASES
alias r='ranger'
alias sr='sudo ranger'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias c='cd ~/.config && r'
alias p='sudo pacman -S $1'
alias rec='wf-recorder -g "$(slurp)"'
alias n='neofetch'
alias bat='cat /sys/class/power_supply/BAT0/capacity'
alias hypr='cd ~/.config/hypr/ && ranger'
# Scrips
alias g='python /home/stian/.config/scripts/gpt.py'

# run C++ code. 
# Ex: cc test
# Will run test.cpp
cc() {
    g++ "$1.cpp" -o "$1" && ./"$1"
}
