#! /bin/sh

export EDITOR=nvim
export VISUAL=nvim
export PAGER=less

# Prevent ranger using default config
RANGER_LOAD_DEFAULT_RC=FALSE

#################################################################
#								#
#			BSPWM CONFIGURATION			#
#								#
#################################################################

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 6 7 8 9
#bspc monitor DVI-D-0 -d 8 9

bspc config border_width         4
bspc config window_gap          12
bspc config top_padding 	30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# BORDER

bspc config focused_border_color	"#8be9fd"
bspc config normal_border_color		"#282a36"
bspc config active_border_color		"#ff79c6"

#################################################################
#								#
#			 WINDOW RULES				#
#								#
#################################################################

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Zathura state=tiled
bspc rule -a kittyToggle desktop='^1' state=floating focus=on follow=on sticky=on hidden=on center=true locked=on rectangle=1920x1000+0+0

#################################################################
#								#
#			   AUTOSTART				#
#								#
#################################################################

# KEYBOARD

kmonad ~/.config/kmonad/air60.kbd &				# KEYBOARD MAPPING
setxkbmap eu &							# KEYBOARD LAYOUT

# DISPLAY 

#xrandr --output DP-0 --primary --mode 3840x2160 --rate 144  --pos 0x0 --rotate normal --output HDMI-0 --mode 1920x1080 --rate 60 --rotate right --right-of DP-0 
~/.screenlayout/default.sh &
# TOPBAR

~/.config/polybar/launch.sh &					# POLYBAR LAUNCH SCRIPT

# INDICATORS AND APPLETS

nm-applet --indicator &						# NETWORK
blueman-applet &						# BLUETOOTH

# STYLING

xsetroot -cursor_name left_ptr &				# CURSOR
nitrogen --restore &						# WALLPAPER
picom -b &							# BLUR AND STUFF
# OTHER

# Notifications
/usr/bin/dunst &						# NOTIFICATIONS
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &	# POLKIT AUTHENTICATION

# Applications
kitty --class kittyToggle & 

# Success notification
notify-send "Reload success!"

