#! /bin/sh

#################################################################
#								#
#			BSPWM CONFIGURATION			#
#								#
#################################################################

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 6 7 8 9
#bspc monitor DVI-D-0 -d 8 9

bspc config border_width         4
bspc config window_gap          12
bspc config top_padding 	30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# BORDER

bspc config focused_border_color	"#8be9fd"
bspc config normal_border_color		"#282a36"
bspc config active_border_color		"#ff79c6"

#################################################################
#								#
#			 WINDOW RULES				#
#								#
#################################################################

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Zathura state=tiled

#################################################################
#								#
#			   AUTOSTART				#
#								#
#################################################################

~/.scripts/autostart.sh &

# Success notification
notify-send "Reload success!"
